In [1]:
import numpy as np

my_array = np.arange(50, 101)

print(my_array)

[ 50  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67
  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85
  86  87  88  89  90  91  92  93  94  95  96  97  98  99 100]


In [2]:
import numpy as np


ones_array = np.ones(10)


zeros_array = np.zeros(10)


sixes_array = np.full(10, 6)


combined_array = np.concatenate((ones_array, zeros_array, sixes_array))


print(combined_array)



[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 6. 6. 6. 6.
 6. 6. 6. 6. 6. 6.]


In [3]:
import numpy as np
my_array = np.arange(20, 32).reshape(3, 4)
print(my_array)

[[20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [4]:
import numpy as np
my_array = np.eye(3)
print(my_array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [5]:
import numpy as np
my_array = np.diag(np.arange(1, 6))
print(my_array)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [6]:
import numpy as np

my_array = np.array([[1, 4, 3],
                     [5, 2, 6],
                     [7, 9, 8]])


total_sum = np.sum(my_array)
column_sums = np.sum(my_array, axis=0)
row_sums = np.sum(my_array, axis=1)


print(f"Нийт: {total_sum}")
print(f"Баганы нийлбэр: {column_sums}")
print(f"Мөрийн нийлбэр: {row_sums}")

Нийт: 45
Баганы нийлбэр: [13 15 17]
Мөрийн нийлбэр: [ 8 13 24]
